### ISSUE TITLE
Address

### ISSUE THREAD

**Issue by RoomanSr** [williamsmithza/PlatinumCore#1]
I have complied and running. How do I create an address to use in Ubuntu ? Do not have a cli program.

Thanks.

**Comment by williamsmithza** [comment]
After starting Daemon ./PlatinumCored getnewaddress

**Comment by RoomanSr** [comment]
Ok, so you use the "d" command, thanks ! That worked.

**Comment by williamsmithza** [comment]
No issue just use  ./PlatinumCored getnewaddress and ./PlatinumCored getinfo etc....
